// +build !ignore_autogenerated

// Code generated by deepcopy-gen. DO NOT EDIT.

package v1alpha1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Car) DeepCopyInto(out *Car) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	out.Status = in.Status
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Car.
func (in *Car) DeepCopy() *Car {
	if in == nil {
		return nil
	}
	out := new(Car)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *Car) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CarSpec) DeepCopyInto(out *CarSpec) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CarSpec.
func (in *CarSpec) DeepCopy() *CarSpec {
	if in == nil {
		return nil
	}
	out := new(CarSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CarStatus) DeepCopyInto(out *CarStatus) {
	*out = *in
	out.VehicleStatus = in.VehicleStatus
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CarStatus.
func (in *CarStatus) DeepCopy() *CarStatus {
	if in == nil {
		return nil
	}
	out := new(CarStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Motorcycle) DeepCopyInto(out *Motorcycle) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	out.Status = in.Status
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Motorcycle.
func (in *Motorcycle) DeepCopy() *Motorcycle {
	if in == nil {
		return nil
	}
	out := new(Motorcycle)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *Motorcycle) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MotorcycleSpec) DeepCopyInto(out *MotorcycleSpec) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MotorcycleSpec.
func (in *MotorcycleSpec) DeepCopy() *MotorcycleSpec {
	if in == nil {
		return nil
	}
	out := new(MotorcycleSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MotorcycleStatus) DeepCopyInto(out *MotorcycleStatus) {
	*out = *in
	out.VehicleStatus = in.VehicleStatus
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MotorcycleStatus.
func (in *MotorcycleStatus) DeepCopy() *MotorcycleStatus {
	if in == nil {
		return nil
	}
	out := new(MotorcycleStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VehicleStatus) DeepCopyInto(out *VehicleStatus) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VehicleStatus.
func (in *VehicleStatus) DeepCopy() *VehicleStatus {
	if in == nil {
		return nil
	}
	out := new(VehicleStatus)
	in.DeepCopyInto(out)
	return out
}
