// +build !ignore_autogenerated

// Code generated by conversion-gen. DO NOT EDIT.

package v1alpha1

import (
	sample "github.com/weaveworks/libgitops/cmd/sample-app/apis/sample"
	conversion "k8s.io/apimachinery/pkg/conversion"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

func init() {
	localSchemeBuilder.Register(RegisterConversions)
}

// RegisterConversions adds conversion functions to the given scheme.
// Public to allow building arbitrary schemes.
func RegisterConversions(s *runtime.Scheme) error {
	if err := s.AddGeneratedConversionFunc((*Car)(nil), (*sample.Car)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_Car_To_sample_Car(a.(*Car), b.(*sample.Car), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*sample.Car)(nil), (*Car)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_sample_Car_To_v1alpha1_Car(a.(*sample.Car), b.(*Car), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*CarSpec)(nil), (*sample.CarSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_CarSpec_To_sample_CarSpec(a.(*CarSpec), b.(*sample.CarSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*sample.CarSpec)(nil), (*CarSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_sample_CarSpec_To_v1alpha1_CarSpec(a.(*sample.CarSpec), b.(*CarSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*CarStatus)(nil), (*sample.CarStatus)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_CarStatus_To_sample_CarStatus(a.(*CarStatus), b.(*sample.CarStatus), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*sample.CarStatus)(nil), (*CarStatus)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_sample_CarStatus_To_v1alpha1_CarStatus(a.(*sample.CarStatus), b.(*CarStatus), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*Motorcycle)(nil), (*sample.Motorcycle)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_Motorcycle_To_sample_Motorcycle(a.(*Motorcycle), b.(*sample.Motorcycle), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*sample.Motorcycle)(nil), (*Motorcycle)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_sample_Motorcycle_To_v1alpha1_Motorcycle(a.(*sample.Motorcycle), b.(*Motorcycle), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*MotorcycleSpec)(nil), (*sample.MotorcycleSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_MotorcycleSpec_To_sample_MotorcycleSpec(a.(*MotorcycleSpec), b.(*sample.MotorcycleSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*sample.MotorcycleSpec)(nil), (*MotorcycleSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_sample_MotorcycleSpec_To_v1alpha1_MotorcycleSpec(a.(*sample.MotorcycleSpec), b.(*MotorcycleSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*MotorcycleStatus)(nil), (*sample.MotorcycleStatus)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_MotorcycleStatus_To_sample_MotorcycleStatus(a.(*MotorcycleStatus), b.(*sample.MotorcycleStatus), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*sample.MotorcycleStatus)(nil), (*MotorcycleStatus)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_sample_MotorcycleStatus_To_v1alpha1_MotorcycleStatus(a.(*sample.MotorcycleStatus), b.(*MotorcycleStatus), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*VehicleStatus)(nil), (*sample.VehicleStatus)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_VehicleStatus_To_sample_VehicleStatus(a.(*VehicleStatus), b.(*sample.VehicleStatus), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*sample.VehicleStatus)(nil), (*VehicleStatus)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_sample_VehicleStatus_To_v1alpha1_VehicleStatus(a.(*sample.VehicleStatus), b.(*VehicleStatus), scope)
	}); err != nil {
		return err
	}
	return nil
}

func autoConvert_v1alpha1_Car_To_sample_Car(in *Car, out *sample.Car, s conversion.Scope) error {
	out.TypeMeta = in.TypeMeta
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_v1alpha1_CarSpec_To_sample_CarSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	if err := Convert_v1alpha1_CarStatus_To_sample_CarStatus(&in.Status, &out.Status, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1alpha1_Car_To_sample_Car is an autogenerated conversion function.
func Convert_v1alpha1_Car_To_sample_Car(in *Car, out *sample.Car, s conversion.Scope) error {
	return autoConvert_v1alpha1_Car_To_sample_Car(in, out, s)
}

func autoConvert_sample_Car_To_v1alpha1_Car(in *sample.Car, out *Car, s conversion.Scope) error {
	out.TypeMeta = in.TypeMeta
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_sample_CarSpec_To_v1alpha1_CarSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	if err := Convert_sample_CarStatus_To_v1alpha1_CarStatus(&in.Status, &out.Status, s); err != nil {
		return err
	}
	return nil
}

// Convert_sample_Car_To_v1alpha1_Car is an autogenerated conversion function.
func Convert_sample_Car_To_v1alpha1_Car(in *sample.Car, out *Car, s conversion.Scope) error {
	return autoConvert_sample_Car_To_v1alpha1_Car(in, out, s)
}

func autoConvert_v1alpha1_CarSpec_To_sample_CarSpec(in *CarSpec, out *sample.CarSpec, s conversion.Scope) error {
	out.Engine = in.Engine
	out.YearModel = in.YearModel
	out.Brand = in.Brand
	return nil
}

// Convert_v1alpha1_CarSpec_To_sample_CarSpec is an autogenerated conversion function.
func Convert_v1alpha1_CarSpec_To_sample_CarSpec(in *CarSpec, out *sample.CarSpec, s conversion.Scope) error {
	return autoConvert_v1alpha1_CarSpec_To_sample_CarSpec(in, out, s)
}

func autoConvert_sample_CarSpec_To_v1alpha1_CarSpec(in *sample.CarSpec, out *CarSpec, s conversion.Scope) error {
	out.Engine = in.Engine
	out.YearModel = in.YearModel
	out.Brand = in.Brand
	return nil
}

// Convert_sample_CarSpec_To_v1alpha1_CarSpec is an autogenerated conversion function.
func Convert_sample_CarSpec_To_v1alpha1_CarSpec(in *sample.CarSpec, out *CarSpec, s conversion.Scope) error {
	return autoConvert_sample_CarSpec_To_v1alpha1_CarSpec(in, out, s)
}

func autoConvert_v1alpha1_CarStatus_To_sample_CarStatus(in *CarStatus, out *sample.CarStatus, s conversion.Scope) error {
	if err := Convert_v1alpha1_VehicleStatus_To_sample_VehicleStatus(&in.VehicleStatus, &out.VehicleStatus, s); err != nil {
		return err
	}
	out.Persons = in.Persons
	return nil
}

// Convert_v1alpha1_CarStatus_To_sample_CarStatus is an autogenerated conversion function.
func Convert_v1alpha1_CarStatus_To_sample_CarStatus(in *CarStatus, out *sample.CarStatus, s conversion.Scope) error {
	return autoConvert_v1alpha1_CarStatus_To_sample_CarStatus(in, out, s)
}

func autoConvert_sample_CarStatus_To_v1alpha1_CarStatus(in *sample.CarStatus, out *CarStatus, s conversion.Scope) error {
	if err := Convert_sample_VehicleStatus_To_v1alpha1_VehicleStatus(&in.VehicleStatus, &out.VehicleStatus, s); err != nil {
		return err
	}
	out.Persons = in.Persons
	return nil
}

// Convert_sample_CarStatus_To_v1alpha1_CarStatus is an autogenerated conversion function.
func Convert_sample_CarStatus_To_v1alpha1_CarStatus(in *sample.CarStatus, out *CarStatus, s conversion.Scope) error {
	return autoConvert_sample_CarStatus_To_v1alpha1_CarStatus(in, out, s)
}

func autoConvert_v1alpha1_Motorcycle_To_sample_Motorcycle(in *Motorcycle, out *sample.Motorcycle, s conversion.Scope) error {
	out.TypeMeta = in.TypeMeta
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_v1alpha1_MotorcycleSpec_To_sample_MotorcycleSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	if err := Convert_v1alpha1_MotorcycleStatus_To_sample_MotorcycleStatus(&in.Status, &out.Status, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1alpha1_Motorcycle_To_sample_Motorcycle is an autogenerated conversion function.
func Convert_v1alpha1_Motorcycle_To_sample_Motorcycle(in *Motorcycle, out *sample.Motorcycle, s conversion.Scope) error {
	return autoConvert_v1alpha1_Motorcycle_To_sample_Motorcycle(in, out, s)
}

func autoConvert_sample_Motorcycle_To_v1alpha1_Motorcycle(in *sample.Motorcycle, out *Motorcycle, s conversion.Scope) error {
	out.TypeMeta = in.TypeMeta
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_sample_MotorcycleSpec_To_v1alpha1_MotorcycleSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	if err := Convert_sample_MotorcycleStatus_To_v1alpha1_MotorcycleStatus(&in.Status, &out.Status, s); err != nil {
		return err
	}
	return nil
}

// Convert_sample_Motorcycle_To_v1alpha1_Motorcycle is an autogenerated conversion function.
func Convert_sample_Motorcycle_To_v1alpha1_Motorcycle(in *sample.Motorcycle, out *Motorcycle, s conversion.Scope) error {
	return autoConvert_sample_Motorcycle_To_v1alpha1_Motorcycle(in, out, s)
}

func autoConvert_v1alpha1_MotorcycleSpec_To_sample_MotorcycleSpec(in *MotorcycleSpec, out *sample.MotorcycleSpec, s conversion.Scope) error {
	out.Color = in.Color
	out.BodyType = in.BodyType
	return nil
}

// Convert_v1alpha1_MotorcycleSpec_To_sample_MotorcycleSpec is an autogenerated conversion function.
func Convert_v1alpha1_MotorcycleSpec_To_sample_MotorcycleSpec(in *MotorcycleSpec, out *sample.MotorcycleSpec, s conversion.Scope) error {
	return autoConvert_v1alpha1_MotorcycleSpec_To_sample_MotorcycleSpec(in, out, s)
}

func autoConvert_sample_MotorcycleSpec_To_v1alpha1_MotorcycleSpec(in *sample.MotorcycleSpec, out *MotorcycleSpec, s conversion.Scope) error {
	out.Color = in.Color
	out.BodyType = in.BodyType
	return nil
}

// Convert_sample_MotorcycleSpec_To_v1alpha1_MotorcycleSpec is an autogenerated conversion function.
func Convert_sample_MotorcycleSpec_To_v1alpha1_MotorcycleSpec(in *sample.MotorcycleSpec, out *MotorcycleSpec, s conversion.Scope) error {
	return autoConvert_sample_MotorcycleSpec_To_v1alpha1_MotorcycleSpec(in, out, s)
}

func autoConvert_v1alpha1_MotorcycleStatus_To_sample_MotorcycleStatus(in *MotorcycleStatus, out *sample.MotorcycleStatus, s conversion.Scope) error {
	if err := Convert_v1alpha1_VehicleStatus_To_sample_VehicleStatus(&in.VehicleStatus, &out.VehicleStatus, s); err != nil {
		return err
	}
	out.CurrentWeight = in.CurrentWeight
	return nil
}

// Convert_v1alpha1_MotorcycleStatus_To_sample_MotorcycleStatus is an autogenerated conversion function.
func Convert_v1alpha1_MotorcycleStatus_To_sample_MotorcycleStatus(in *MotorcycleStatus, out *sample.MotorcycleStatus, s conversion.Scope) error {
	return autoConvert_v1alpha1_MotorcycleStatus_To_sample_MotorcycleStatus(in, out, s)
}

func autoConvert_sample_MotorcycleStatus_To_v1alpha1_MotorcycleStatus(in *sample.MotorcycleStatus, out *MotorcycleStatus, s conversion.Scope) error {
	if err := Convert_sample_VehicleStatus_To_v1alpha1_VehicleStatus(&in.VehicleStatus, &out.VehicleStatus, s); err != nil {
		return err
	}
	out.CurrentWeight = in.CurrentWeight
	return nil
}

// Convert_sample_MotorcycleStatus_To_v1alpha1_MotorcycleStatus is an autogenerated conversion function.
func Convert_sample_MotorcycleStatus_To_v1alpha1_MotorcycleStatus(in *sample.MotorcycleStatus, out *MotorcycleStatus, s conversion.Scope) error {
	return autoConvert_sample_MotorcycleStatus_To_v1alpha1_MotorcycleStatus(in, out, s)
}

func autoConvert_v1alpha1_VehicleStatus_To_sample_VehicleStatus(in *VehicleStatus, out *sample.VehicleStatus, s conversion.Scope) error {
	out.Speed = in.Speed
	out.Acceleration = in.Acceleration
	out.Distance = in.Distance
	return nil
}

// Convert_v1alpha1_VehicleStatus_To_sample_VehicleStatus is an autogenerated conversion function.
func Convert_v1alpha1_VehicleStatus_To_sample_VehicleStatus(in *VehicleStatus, out *sample.VehicleStatus, s conversion.Scope) error {
	return autoConvert_v1alpha1_VehicleStatus_To_sample_VehicleStatus(in, out, s)
}

func autoConvert_sample_VehicleStatus_To_v1alpha1_VehicleStatus(in *sample.VehicleStatus, out *VehicleStatus, s conversion.Scope) error {
	out.Speed = in.Speed
	out.Acceleration = in.Acceleration
	out.Distance = in.Distance
	return nil
}

// Convert_sample_VehicleStatus_To_v1alpha1_VehicleStatus is an autogenerated conversion function.
func Convert_sample_VehicleStatus_To_v1alpha1_VehicleStatus(in *sample.VehicleStatus, out *VehicleStatus, s conversion.Scope) error {
	return autoConvert_sample_VehicleStatus_To_v1alpha1_VehicleStatus(in, out, s)
}
