// +build !ignore_autogenerated

// Code generated by defaulter-gen. DO NOT EDIT.

package v1alpha1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// RegisterDefaults adds defaulters functions to the given scheme.
// Public to allow building arbitrary schemes.
// All generated defaulters are covering - they call all nested defaulters.
func RegisterDefaults(scheme *runtime.Scheme) error {
	scheme.AddTypeDefaultingFunc(&Car{}, func(obj interface{}) { SetObjectDefaults_Car(obj.(*Car)) })
	scheme.AddTypeDefaultingFunc(&Motorcycle{}, func(obj interface{}) { SetObjectDefaults_Motorcycle(obj.(*Motorcycle)) })
	return nil
}

func SetObjectDefaults_Car(in *Car) {
	SetDefaults_CarSpec(&in.Spec)
}

func SetObjectDefaults_Motorcycle(in *Motorcycle) {
	SetDefaults_MotorcycleSpec(&in.Spec)
}
