/*
	Note: This file is autogenerated! Do not edit it manually!
	Edit client_motorcycle_template.go instead, and run
	hack/generate-client.sh afterwards.
*/

package client

import (
	"fmt"

	api "github.com/weaveworks/gitops-toolkit/cmd/sample-app/apis/sample"

	log "github.com/sirupsen/logrus"
	"github.com/weaveworks/gitops-toolkit/pkg/runtime"
	"github.com/weaveworks/gitops-toolkit/pkg/storage"
	"github.com/weaveworks/gitops-toolkit/pkg/storage/filterer"
	"k8s.io/apimachinery/pkg/runtime/schema"
)

// MotorcycleClient is an interface for accessing Motorcycle-specific API objects
type MotorcycleClient interface {
	// New returns a new Motorcycle
	New() *api.Motorcycle
	// Get returns the Motorcycle matching given UID from the storage
	Get(runtime.UID) (*api.Motorcycle, error)
	// Set saves the given Motorcycle into persistent storage
	Set(*api.Motorcycle) error
	// Patch performs a strategic merge patch on the object with
	// the given UID, using the byte-encoded patch given
	Patch(runtime.UID, []byte) error
	// Find returns the Motorcycle matching the given filter, filters can
	// match e.g. the Object's Name, UID or a specific property
	Find(filter filterer.BaseFilter) (*api.Motorcycle, error)
	// FindAll returns multiple Motorcycles matching the given filter, filters can
	// match e.g. the Object's Name, UID or a specific property
	FindAll(filter filterer.BaseFilter) ([]*api.Motorcycle, error)
	// Delete deletes the Motorcycle with the given UID from the storage
	Delete(uid runtime.UID) error
	// List returns a list of all Motorcycles available
	List() ([]*api.Motorcycle, error)
}

// Motorcycles returns the MotorcycleClient for the IgniteInternalClient instance
func (c *SampleInternalClient) Motorcycles() MotorcycleClient {
	if c.motorcycleClient == nil {
		c.motorcycleClient = newMotorcycleClient(c.storage, c.gv)
	}

	return c.motorcycleClient
}

// motorcycleClient is a struct implementing the MotorcycleClient interface
// It uses a shared storage instance passed from the Client together with its own Filterer
type motorcycleClient struct {
	storage  storage.Storage
	filterer *filterer.Filterer
	gvk      schema.GroupVersionKind
}

// newMotorcycleClient builds the motorcycleClient struct using the storage implementation and a new Filterer
func newMotorcycleClient(s storage.Storage, gv schema.GroupVersion) MotorcycleClient {
	return &motorcycleClient{
		storage:  s,
		filterer: filterer.NewFilterer(s),
		gvk:      gv.WithKind(api.KindMotorcycle.Title()),
	}
}

// New returns a new Object of its kind
func (c *motorcycleClient) New() *api.Motorcycle {
	log.Tracef("Client.New; GVK: %v", c.gvk)
	obj, err := c.storage.New(c.gvk)
	if err != nil {
		panic(fmt.Sprintf("Client.New must not return an error: %v", err))
	}
	return obj.(*api.Motorcycle)
}

// Find returns a single Motorcycle based on the given Filter
func (c *motorcycleClient) Find(filter filterer.BaseFilter) (*api.Motorcycle, error) {
	log.Tracef("Client.Find; GVK: %v", c.gvk)
	object, err := c.filterer.Find(c.gvk, filter)
	if err != nil {
		return nil, err
	}

	return object.(*api.Motorcycle), nil
}

// FindAll returns multiple Motorcycles based on the given Filter
func (c *motorcycleClient) FindAll(filter filterer.BaseFilter) ([]*api.Motorcycle, error) {
	log.Tracef("Client.FindAll; GVK: %v", c.gvk)
	matches, err := c.filterer.FindAll(c.gvk, filter)
	if err != nil {
		return nil, err
	}

	results := make([]*api.Motorcycle, 0, len(matches))
	for _, item := range matches {
		results = append(results, item.(*api.Motorcycle))
	}

	return results, nil
}

// Get returns the Motorcycle matching given UID from the storage
func (c *motorcycleClient) Get(uid runtime.UID) (*api.Motorcycle, error) {
	log.Tracef("Client.Get; UID: %q, GVK: %v", uid, c.gvk)
	object, err := c.storage.Get(c.gvk, uid)
	if err != nil {
		return nil, err
	}

	return object.(*api.Motorcycle), nil
}

// Set saves the given Motorcycle into the persistent storage
func (c *motorcycleClient) Set(motorcycle *api.Motorcycle) error {
	log.Tracef("Client.Set; UID: %q, GVK: %v", motorcycle.GetUID(), c.gvk)
	return c.storage.Set(c.gvk, motorcycle)
}

// Patch performs a strategic merge patch on the object with
// the given UID, using the byte-encoded patch given
func (c *motorcycleClient) Patch(uid runtime.UID, patch []byte) error {
	return c.storage.Patch(c.gvk, uid, patch)
}

// Delete deletes the Motorcycle from the storage
func (c *motorcycleClient) Delete(uid runtime.UID) error {
	log.Tracef("Client.Delete; UID: %q, GVK: %v", uid, c.gvk)
	return c.storage.Delete(c.gvk, uid)
}

// List returns a list of all Motorcycles available
func (c *motorcycleClient) List() ([]*api.Motorcycle, error) {
	log.Tracef("Client.List; GVK: %v", c.gvk)
	list, err := c.storage.List(c.gvk)
	if err != nil {
		return nil, err
	}

	results := make([]*api.Motorcycle, 0, len(list))
	for _, item := range list {
		results = append(results, item.(*api.Motorcycle))
	}

	return results, nil
}
